-- CreateTable
CREATE TABLE `Employee` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `username` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL DEFAULT 'EMPLOYEE',
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `lastLogin` DATETIME(3) NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `profilePicture` LONGTEXT NULL,
    `nickName` VARCHAR(191) NULL,
    `dob` VARCHAR(191) NULL,
    `age` INTEGER NULL,
    `gender` VARCHAR(191) NULL,
    `maritalStatus` VARCHAR(191) NULL,
    `nationality` VARCHAR(191) NULL,
    `skills` VARCHAR(191) NULL,
    `linkedin` VARCHAR(191) NULL,
    `twitter` VARCHAR(191) NULL,
    `employeeId` VARCHAR(191) NOT NULL,
    `employmentType` VARCHAR(191) NOT NULL,
    `jobTitle` VARCHAR(191) NOT NULL,
    `position` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NULL,
    `businessUnit` VARCHAR(191) NULL,
    `reportingManager` VARCHAR(191) NULL,
    `workLocation` VARCHAR(191) NOT NULL,
    `remoteRate` DOUBLE NULL,
    `onsiteRate` DOUBLE NULL,
    `rateBasis` VARCHAR(191) NULL,
    `dateOfJoining` DATETIME(3) NULL,
    `employeeStatus` VARCHAR(191) NULL,
    `leavePolicy` VARCHAR(191) NULL,
    `timesheetRequired` BOOLEAN NOT NULL DEFAULT false,
    `workPhone` VARCHAR(191) NULL,
    `personalPhone` VARCHAR(191) NULL,
    `presentAddress` VARCHAR(191) NULL,
    `permanentAddress` VARCHAR(191) NULL,
    `emergencyName` VARCHAR(191) NULL,
    `relationship` VARCHAR(191) NULL,
    `emergencyPhone` VARCHAR(191) NULL,
    `bankName` VARCHAR(191) NULL,
    `bankCountry` VARCHAR(191) NULL,
    `accountType` VARCHAR(191) NULL,
    `accountNumber` VARCHAR(191) NULL,
    `iban` VARCHAR(191) NULL,
    `routingCode` VARCHAR(191) NULL,
    `swiftCode` VARCHAR(191) NULL,
    `ifscCode` VARCHAR(191) NULL,
    `firstEntry` DATETIME(3) NULL,
    `latestExit` DATETIME(3) NULL,
    `latestEntry` DATETIME(3) NULL,
    `daysFromEntry` INTEGER NULL,
    `exitDate` DATETIME(3) NULL,
    `exitReason` VARCHAR(191) NULL,
    `canJoinAgain` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `Employee_username_key`(`username`),
    UNIQUE INDEX `Employee_email_key`(`email`),
    UNIQUE INDEX `Employee_employeeId_key`(`employeeId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
